#!/usr/bin/env python3

import argparse
import ast
import json
import os
from pathlib import Path
from typing import Any


_OUTPUT_PATH = "nodejs/private/lief_sources.bzl"


def _read_gyp(path: Path) -> dict[str, Any]:
    value = ast.literal_eval(path.read_text())
    if not isinstance(value, dict) or not isinstance(value.get("variables"), dict):
        raise ValueError(f"{path} must contain a variables dictionary")
    return value


def _source_list(variables: dict[str, Any], name: str, suffix: str) -> list[str]:
    sources = variables.get(name)
    if not isinstance(sources, list) or not sources:
        raise ValueError(f"{name} must be a nonempty list")
    if any(not isinstance(source, str) or not source.endswith(suffix) for source in sources):
        raise ValueError(f"{name} must contain only {suffix} sources")
    if len(sources) != len(set(sources)):
        raise ValueError(f"{name} contains duplicate sources")
    return sources


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--gyp", required=True, type=Path)
    arguments = parser.parse_args()

    variables = _read_gyp(arguments.gyp)["variables"]
    source_groups = {
        "LIEF_SOURCES": _source_list(variables, "lief_sources", ".cpp"),
        "LIEF_THIRD_PARTY_SOURCES": _source_list(
            variables,
            "lief_third_party_sources",
            ".c",
        ),
    }

    lines = [
        '"""Generated LIEF source inventory for Node.js 26.3.1."""',
        "",
        "# Generated by: bazel run //tools/lief_sources:generate",
        "# Do not edit manually.",
    ]
    for name, sources in source_groups.items():
        lines.extend(["", f"{name} = ["])
        lines.extend(
            f"    {json.dumps(f'deps/LIEF/{source}')}," for source in sources
        )
        lines.append("]")
    lines.append("")

    workspace = Path(os.environ["BUILD_WORKSPACE_DIRECTORY"])
    (workspace / _OUTPUT_PATH).write_text("\n".join(lines))


if __name__ == "__main__":
    main()
