module(
    name = "nodejs_integration_test",
    version = "0.0.0",
)

bazel_dep(name = "aspect_rules_js", version = "3.3.1")
bazel_dep(name = "nodejs", version = "0.0.0")
bazel_dep(name = "llvm", version = "0.8.8")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.19")
bazel_dep(name = "rules_nodejs", version = "6.7.5")
bazel_dep(name = "rules_rs", version = "0.0.86")
bazel_dep(name = "rules_shell", version = "0.6.1")

local_path_override(
    module_name = "nodejs",
    path = "../..",
)

rust = use_extension("@rules_rs//rs:rules_rust_reexported_extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    extra_target_triples = [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "x86_64-unknown-linux-gnu",
    ],
    rustfmt_version = "1.92.0",
    versions = ["1.92.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

nodejs = use_extension("@nodejs//nodejs:extensions.bzl", "nodejs")
nodejs.version(version = "26.3.1")
use_repo(nodejs, "nodejs_26_3_1", "nodejs_crates_26_3_1", "nodejs_icu_26_3_1", "nodejs_toolchains", "v8")

register_toolchains("@nodejs_toolchains//:all")

nodejs_crates = use_extension("@rules_rs//rs:extensions.bzl", "crate")
nodejs_crates.from_cargo(
    name = "nodejs_crates",
    cargo_lock = "@nodejs_crates_26_3_1//:Cargo.lock",
    cargo_toml = "@nodejs_crates_26_3_1//:Cargo.toml",
    platform_triples = [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "x86_64-unknown-linux-gnu",
    ],
    use_legacy_rules_rust_platforms = True,
)
use_repo(nodejs_crates, "nodejs_crates")

inject_repo(nodejs, nodejs_crates = "nodejs_crates")
