#!/usr/bin/env python3

import argparse
import ast
import json
import os
from pathlib import Path
from typing import Any


_OUTPUT_PATH = "nodejs/private/openssl_sources.bzl"


def _read_gypi(path: Path) -> dict[str, Any]:
    value = ast.literal_eval(path.read_text())
    if not isinstance(value, dict) or not isinstance(value.get("variables"), dict):
        raise ValueError(f"{path} must contain a variables dictionary")
    return value


def _source_path(path: str) -> str:
    normalized = path.removeprefix("./")
    return f"deps/openssl/{normalized}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--linux-arm64", required=True, type=Path)
    parser.add_argument("--linux-x86-64", required=True, type=Path)
    parser.add_argument("--macos-arm64", required=True, type=Path)
    parser.add_argument("--macos-x86-64", required=True, type=Path)
    parser.add_argument("--windows-arm64", required=True, type=Path)
    parser.add_argument("--windows-x86-64", required=True, type=Path)
    arguments = parser.parse_args()

    gypi_by_platform = {
        "linux_arm64": _read_gypi(arguments.linux_arm64),
        "linux_x86_64": _read_gypi(arguments.linux_x86_64),
        "macos_arm64": _read_gypi(arguments.macos_arm64),
        "macos_x86_64": _read_gypi(arguments.macos_x86_64),
        "windows_arm64": _read_gypi(arguments.windows_arm64),
        "windows_x86_64": _read_gypi(arguments.windows_x86_64),
    }

    common_sources_with_duplicates = gypi_by_platform["linux_x86_64"]["variables"][
        "openssl_sources"
    ]
    if not common_sources_with_duplicates or any(
        not source.endswith(".c") for source in common_sources_with_duplicates
    ):
        raise ValueError("openssl_sources must contain only C sources")
    common_sources = list(dict.fromkeys(common_sources_with_duplicates))
    common_source_set = set(common_sources)

    platform_sources: dict[str, list[str]] = {}
    platform_defines: dict[str, list[str]] = {}
    for platform, gypi in gypi_by_platform.items():
        variables = gypi["variables"]
        platform_common_sources = variables.get("openssl_sources")
        if not platform_common_sources:
            raise ValueError(f"{platform} openssl_sources is empty")
        missing_common_sources = common_source_set - set(platform_common_sources)
        if missing_common_sources:
            raise ValueError(
                f"{platform} openssl_sources is missing {sorted(missing_common_sources)}"
            )
        extra_common_sources = [
            source
            for source in dict.fromkeys(platform_common_sources)
            if source not in common_source_set
        ]
        generated_source_key = next(
            key for key in variables if key.startswith("openssl_sources_")
        )
        define_key = next(
            key for key in variables if key.startswith("openssl_defines_")
        )
        generated_sources = variables[generated_source_key]
        non_c_sources = {source for source in generated_sources if not source.endswith(".c")}
        expected_non_c_sources: set[str] = set()
        if platform.startswith("linux_"):
            architecture = (
                "linux-aarch64" if platform == "linux_arm64" else "linux-x86_64"
            )
            expected_non_c_sources = {
                f"./config/archs/{architecture}/no-asm/providers/fips.ld",
                f"./config/archs/{architecture}/no-asm/providers/legacy.ld",
            }
        if non_c_sources != expected_non_c_sources:
            raise ValueError(f"unexpected {platform} non-C sources: {non_c_sources}")
        platform_sources[platform] = [
            _source_path(source) for source in extra_common_sources
        ] + [
            _source_path(source)
            for source in generated_sources
            if source.endswith(".c")
        ]
        platform_defines[platform] = variables[define_key]

    lines = [
        '"""Generated OpenSSL no-assembly source inventory for Node.js 26.3.1."""',
        "",
        "# Generated by: bazel run //tools/openssl_sources:generate",
        "# Do not edit manually.",
        "",
        "OPENSSL_NO_ASM_SOURCES = [",
    ]
    lines.extend(f"    {json.dumps(_source_path(source))}," for source in common_sources)
    lines.extend([
        "]",
        "",
        "OPENSSL_NO_ASM_PLATFORM_SOURCES = {",
    ])
    for platform, sources in platform_sources.items():
        lines.append(f"    {json.dumps(platform)}: [")
        lines.extend(f"        {json.dumps(source)}," for source in sources)
        lines.append("    ],")
    lines.extend([
        "}",
        "",
        "OPENSSL_NO_ASM_PLATFORM_DEFINES = {",
    ])
    for platform, defines in platform_defines.items():
        lines.append(f"    {json.dumps(platform)}: [")
        lines.extend(f"        {json.dumps(define)}," for define in defines)
        lines.append("    ],")
    lines.extend(["}", ""])

    workspace = Path(os.environ["BUILD_WORKSPACE_DIRECTORY"])
    output = workspace / _OUTPUT_PATH
    output.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
