#!/usr/bin/env python3

import argparse
import ast
import json
import os
from pathlib import Path
from typing import Any


_OUTPUT_PATH = "nodejs/private/node_sources.bzl"
_SOURCE_SUFFIXES = (".c", ".cc", ".cpp", ".S")
_HEADER_SUFFIXES = (".h", ".inc", ".tcc")


def _read_gyp(path: Path) -> dict[str, Any]:
    value = ast.literal_eval(path.read_text())
    if not isinstance(value, dict) or not isinstance(value.get("variables"), dict):
        raise ValueError(f"{path} must contain a variables dictionary")
    return value


def _sources(variables: dict[str, Any], name: str) -> list[str]:
    entries = variables.get(name)
    if not isinstance(entries, list) or not entries:
        raise ValueError(f"{name} must be a nonempty list")
    if any(not isinstance(entry, str) for entry in entries):
        raise ValueError(f"{name} must contain only paths")
    unexpected = [
        entry
        for entry in entries
        if not entry.endswith(_SOURCE_SUFFIXES + _HEADER_SUFFIXES)
    ]
    if unexpected:
        raise ValueError(f"{name} contains unexpected paths: {unexpected}")
    sources = [entry for entry in entries if entry.endswith(_SOURCE_SUFFIXES)]
    if len(sources) != len(set(sources)):
        raise ValueError(f"{name} contains duplicate sources")
    return sources


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--node-gyp", required=True, type=Path)
    parser.add_argument("--node-inspector-gypi", required=True, type=Path)
    arguments = parser.parse_args()

    node_variables = _read_gyp(arguments.node_gyp)["variables"]
    inspector_variables = _read_gyp(arguments.node_inspector_gypi)["variables"]
    source_groups = {
        "NODE_SOURCES": _sources(node_variables, "node_sources"),
        "NODE_CRYPTO_SOURCES": _sources(node_variables, "node_crypto_sources"),
        "NODE_FFI_SOURCES": _sources(node_variables, "node_ffi_sources"),
        "NODE_INSPECTOR_SOURCES": _sources(
            inspector_variables,
            "node_inspector_sources",
        ),
        "NODE_SQLITE_SOURCES": _sources(node_variables, "node_sqlite_sources"),
    }

    lines = [
        '"""Generated libnode source inventory for Node.js 26.3.1."""',
        "",
        "# Generated by: bazel run //tools/node_sources:generate",
        "# Do not edit manually.",
    ]
    for name, sources in source_groups.items():
        lines.extend(["", f"{name} = ["])
        lines.extend(f"    {json.dumps(source)}," for source in sources)
        lines.append("]")
    lines.append("")

    workspace = Path(os.environ["BUILD_WORKSPACE_DIRECTORY"])
    (workspace / _OUTPUT_PATH).write_text("\n".join(lines))


if __name__ == "__main__":
    main()
